"""empty message

Revision ID: 28584c6cde62
Revises: d7f1e19d5d00
Create Date: 2020-02-22 15:30:02.928877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28584c6cde62'
down_revision = 'd7f1e19d5d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
